### ISSUE TITLE
1.0.37 requires +nightly

### ISSUE THREAD

**Issue by keltia** [dtolnay/thiserror#205] opened 2022-10-30 21:27 UTC
I think the error message is clear enough and I'm not sure this was intended.
`
atlas-new-rs\atlas-api on  develop [!?⇡] is 📦 v0.3.0 via 🦀 v1.64.0
❯ cargo build
   Compiling schannel v0.1.20
   Compiling clap v4.0.18
   Compiling thiserror v1.0.37
   Compiling log v0.4.17
   Compiling serde_urlencoded v0.7.1
   Compiling serde_json v1.0.87
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\roberto\.cargo\registry\src\github.com-1ecc6299db9ec823\thiserror-1.0.37\src\lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to previous error
warning: build failed, waiting for other jobs to finish...

atlas-new-rs\atlas-api on  develop [!?⇡] is 📦 v0.3.0 via 🦀 v1.64.0 took 2s
❯ cargo +nightly build
   Compiling atlas-api v0.3.0 (C:\Users\roberto\Src\rs\src\atlas-new-rs\atlas-api)
    Finished dev [unoptimized + debuginfo] target(s) in 1.24s
`

**Comment by dtolnay** [comment] 2022-10-30 21:44
Duplicate of #192. I'd guess you are running an old rust-analyzer and/or intellij that has corrupted the `target` directory, but if not, you'll need to provide repro steps in that issue.

**Closed by dtolnay** 2022-10-30 21:44 UTC
