### ISSUE TITLE
Semver breakage on 1.0.37

### ISSUE THREAD

**Issue by Xaeroxe** [dtolnay/thiserror#199] opened 2022-10-16 22:27 UTC
Operating System is Windows 11. Let me know if you need more info.

```
ipc-rpc> cargo update -p thiserror --precise 1.0.36
    Updating crates.io index
ipc-rpc> cargo build
   Compiling ipc-rpc v1.2.5 (C:\Users\kiese\Documents\source_code\ipc-rpc)
    Finished dev [unoptimized + debuginfo] target(s) in 0.84s
ipc-rpc> cargo update -p thiserror --precise 1.0.37
    Updating crates.io index
    Updating thiserror v1.0.36 -> v1.0.37
    Updating thiserror-impl v1.0.36 -> v1.0.37
ipc-rpc> cargo build
   Compiling thiserror v1.0.37
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\kiese\.cargo\registry\src\github.com-1ecc6299db9ec823\thiserror-1.0.37\src\lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to previous error
ipc-rpc> rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
ipc-rpc> cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
```

**Comment by dtolnay** [comment] 2022-10-16 22:36
Duplicate of #192. I'd guess you are running an old rust-analyzer and/or intellij that has corrupted the `target` directory, but if not, you'll need to provide repro steps in that issue.

**Closed by dtolnay** 2022-10-16 22:37 UTC

**Comment by Xaeroxe** [comment] 2022-10-16 22:42
@dtolnay Hm, you're correct that the problem appears to be caused by `rust-analyzer`, but I wouldn't describe this as an old version. `cargo clean` fixes it. I assume rust-analyzer 1.65 or 1.66 has a fix?

```
ipc-rpc> rustup run stable rust-analyzer --version
rust-analyzer 1.64.0 (a55dd71d 2022-09-19)
```

**Comment by Xaeroxe** [comment] 2022-10-16 23:00
It's odd, I just setup this machine. It's never had a different toolchain version on it. Still I can't reproduce the issue on demand. I'll update the other issue if I come up with something.

**Comment by dtolnay** [comment] 2022-10-16 23:05
a55dd71d contains a rust-analyzer from July. I feel like you should only use that if you enjoy hitting all the issues that have been fixed in the last nearly 3 months. https://rust-analyzer.github.io/manual.html#installation explains the supported installation options.
