### ISSUE TITLE
provide_any causes fail in stable channel

### ISSUE THREAD

**Issue by kkolyan** [dtolnay/thiserror#209] opened 2022-11-06 11:25 UTC
Cargo.toml:
```
[package]
name = "this_error_bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
```
main.rs:
```rust
fn main() {
    println!("Hello, world!");
}
```
action:
```
cargo build
```
output:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\kkolyan\.cargo\registry\src\github.com-1ecc6299db9ec823\thiserror-1.0.37\src\lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^
```

**Comment by dtolnay** [comment] 2022-11-06 12:17
Duplicate of #192.

**Closed by dtolnay** 2022-11-06 12:17 UTC

**Comment by qarmin** [comment] 2022-12-20 11:09
Maybe this issue should be pinned?

Quick fix - `cargo clean`
