### ISSUE TITLE
Unresolved import and unstable library feature errors on Rust 1.68.2

### ISSUE THREAD

**Issue by vincent-herlemont** [dtolnay/thiserror#228] opened 2023-04-12 19:00 UTC
I am using stable version Rust 1.68.2 and the `thiserror` crate, but I am encountering errors related to an unresolved import and the use of an unstable library feature.

I try to activate Backtrace like described in the documentation: [latest/thiserror/](https://docs.rs/thiserror/latest/thiserror/).

> A From impl is generated for each variant containing a #[from] attribute.
>
> 
> Note that the variant must not contain any other fields beyond the source error and possibly a backtrace. > A backtrace is captured from within the From impl if there is a field for it.
> 
> ```rust
> #[derive(Error, Debug)]
> pub enum MyError {
>    Io {
>        #[from]
>         source: io::Error,
>         backtrace: Backtrace,
>     },
> }
> ```

Here's the code I am using with the `thiserror` crate:

```rust
use thiserror::Error;
use std::backtrace::Backtrace;

#[derive(Error, Debug)]
pub enum Error {
    Io {
        #[from]
        source: std::io::Error,
        backtrace: Backtrace,
    }
}
```

And my function:

```rust
pub fn open_file(path: &Path) -> Result<File> {
    let file = File::open(path)?;
    Ok(file)
}
```

And my test:

```rust
let file = struct_db::open_file("my_path").unwrap();
```

Output logs:
```bash
error[E0432]: unresolved import `thiserror`
 --> src/error.rs:4:10
  |
4 | #[derive(Error, Debug)]
  |          ^^^^^ no `ThiserrorProvide` in `__private`
  |
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature 'error_generic_member_access'
 --> src/error.rs:4:10
  |
4 | #[derive(Error, Debug)]
  |          ^^^^^
  |
  = note: see issue #99301 <https://github.com/rust-lang/rust/issues/99301> for more information
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `error::Error` doesn't implement `std::fmt::Display`
  --> src/error.rs:5:10
   |
5  | pub enum Error {
   |          ^^^^^ `error::Error` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `error::Error`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
note: required by a bound in `std::error::Error`
  --> /home/user/.rustup/toolchains/1.68.2-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/error.rs:31:26
   |
31 | pub trait Error: Debug + Display {
   |                          ^^^^^^^ required by this bound in `Error`
```

Any suggestions on how to resolve this issue would be greatly appreciated.

---

Related topics that I read to try to resolve this issue: 
- https://github.com/hyperledger/aries-vcx/pull/684
- https://github.com/dtolnay/thiserror/issues/204

**Comment by dtolnay** [comment] 2023-04-12 19:44
This is a duplicate of #204.

**Closed** 2023-04-12 19:52 UTC

**Comment by dzmitry-lahoda** [comment] 2024-01-09 21:46
Currenly anyhow uses some rust nightly features https://github.com/dtolnay/anyhow/blob/master/build.rs if I am not wrong. 

So would be PR thiserror accepted to have similar solution to enable errors in core in rust?
