### ISSUE TITLE
#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by kaitlinsm** [dtolnay/thiserror#206] opened 2022-11-01 15:20 UTC
https://github.com/dtolnay/thiserror/blob/464e2e798eea0985af3c2c16cc55866e2918f774/src/lib.rs#L238

This commit https://github.com/dtolnay/thiserror/commit/460396e8f3ed2f6615372961920fb32daa7376c9 added a call to `!feature(provide_any))]`.

Unfortunately, this breaks builds if you're not on `nightly` release channel:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /[...snip...]/lib.rs:211:34
    |
211 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^
```

It looks like this macro invocation doesn't play well. Is there an alternative way to solve the problem that this change was trying to address?

**Comment by dtolnay** [comment] 2022-11-01 15:41
Duplicate of #192.

**Closed by dtolnay** 2022-11-01 15:41 UTC

**Comment by Nejat** [comment] 2022-11-02 09:14
for what it's worth, to help out anyone else landing on this issue, this happened to me on CLion with the latest complier and rust analyzer, as suggested by a comment on #192, `cargo clean`_*_ resolved the issue for me. 

_* it's the new re-boot windows to fix `X`_ 😋
