### ISSUE TITLE
`provide_any` getting enabled on stable

### ISSUE THREAD

**Issue by akriegman** [dtolnay/thiserror#220] opened 2023-02-03 00:08 UTC
I'm getting the following error:

```
$ cargo run
   Compiling thiserror v1.0.38
   Compiling dasp v0.11.0
error[E0432]: unresolved imports `std::any::Demand`, `std::any::Provider`
 --> /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.38/src/provide.rs:1:16
  |
1 | use std::any::{Demand, Provider};
  |                ^^^^^^  ^^^^^^^^ no `Provider` in `any`
  |                |
  |                no `Demand` in `any`

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.38/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

error[E0635]: unknown feature `provide_any`
   --> /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.38/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

Some errors have detailed explanations: E0432, E0554, E0635.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `thiserror` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

my project compiles successfully with `cargo +nightly run`. What appears to be happening is the build script tries to detect whether the current toolchain supports `provider_any`, and activate the feature just in that case. For some reason with my setup the probe program is compiling successfully even though I'm on stable. Not sure why.

I'm guessing this error will be hard to reproduce and depend heavily on my setup. Please let me know what information I should provide.

**Comment by dtolnay** [comment] 2023-02-03 00:34
Duplicate of #192; it's a rust-analyzer bug.

**Closed by dtolnay** 2023-02-03 00:34 UTC
