### ISSUE TITLE
Version 1.0.35 not compiling on stable rust

### ISSUE THREAD

**Issue by Balduro** [dtolnay/thiserror#193] opened 2022-09-16 19:38 UTC
Hi,
it seems like `feature(provide_any)` is not available on stable rust.
in `lib.rs`

```
error[E0554]: `#![feature]` may not be used on the stable release channel
    |
211 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^
```

I don't think this is intentional.
Version 1.0.34 works.

**Comment by dtolnay** [comment] 2022-09-16 19:45
Closing as a duplicate of #192. If you know of a way to reproduce this, please comment over there.

**Closed by dtolnay** 2022-09-16 19:45 UTC
