### ISSUE TITLE
1.0.37 won't compile on stable release channel in my project's dependency tree

### ISSUE THREAD

**Issue by grantshandy** [dtolnay/thiserror#198] opened 2022-09-30 20:02 UTC
I am currently working on my project and one of my dependencies depends on `1.0.37`. Here's the error I got while compiling:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.37/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to previous error
```

**Comment by grantshandy** [comment] 2022-09-30 20:05
On second thought... it doesn't compile in nightly either!
```
$ cargo build +nightly
   Compiling thiserror v1.0.37
   ...
   Compiling indexmap v1.9.1
   Compiling hashlink v0.8.1
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.37/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by grantshandy** [comment] 2022-09-30 20:08
This was fixed by a `cargo clean` and rebuild. I'm not sure what happened but it went away? sorry for bothering

**Comment by guzkodes** [comment] 2022-10-01 16:15
Having the same issue, ```cargo clean``` does not solve it

**Comment by dtolnay** [comment] 2022-10-01 16:39
Closing as a duplicate of #192. Someone needs to post a repro over there if they have one.

**Closed by dtolnay** 2022-10-01 16:39 UTC
